redis_uri = "redis://127.0.0.1:6379"

[database]
username = "postgres"
password = "password"
database_name = "newsletter"
host = "127.0.0.1"
port = 5432

[application]
port = 8000
hmac_secret = "hmac-secret-token-that-needs-to-be-reset-for-prod-and-needs-to-be-longer-than-64-chars"

[email_client]
base_url = "localhost"
sender_email = "test@gmail.com"
authorization_token = "my-secret-token"
timeout_milliseconds = 10000
