apiVersion: v1
kind: Secret
metadata:
    name: {{ include "zero2prod.fullname" . }}-secret
type: "Opaque"
stringData:
    # DB credentials
    APP_DATABASE__PASSWORD: {{ .Values.global.postgresql.auth.postgresPassword }}
    APP_DATABASE__PORT:  {{ .Values.postgresql.containerPorts.postgresql | quote }}
    APP_DATABASE__NAME: {{ .Values.global.postgresql.auth.database }}
    APP_DATABASE__HOST: {{ .Values.zero2prod.postgresHost }}
    APP_DATABASE__USERNAME: {{ .Values.zero2prod.postgresUsername }}
    APP_APPLICATION__BASE_URL: {{ .Values.zero2prod.baseUrl }}
    APP_EMAIL_CLIENT__SENDER_EMAIL: {{ .Values.zero2prod.senderEmail }}
    APP_EMAIL_CLIENT__AUTHORIZATION_TOKEN: {{ .Values.zero2prod.postmarkAuthToken }}
    APP_APPLICATION__HMAC_SECRET: {{ .Values.zero2prod.hmacSecret }}
